### ISSUE TITLE
Python3 required?

### ISSUE THREAD

**Issue by Argon-** [pigoz/homebrew-mplayer2#11]
My install fails here

```
==> Installing mplayer2
==> Cloning git://git.mplayer2.org/mplayer2.git
Cloning into '/Library/Caches/Homebrew/mplayer2--git'...
remote: Counting objects: 826, done.
remote: Compressing objects: 100% (809/809), done.
remote: Total 826 (delta 99), reused 149 (delta 6)
Receiving objects: 100% (826/826), 2.72 MiB | 847 KiB/s, done.
Resolving deltas: 100% (99/99), done.
==> Generating VERSION from the Homebrew's git cache
==> ./configure --prefix=/usr/local/Cellar/mplayer2/HEAD --cc=/usr/bin/clang --enable-macosx-bundle --enable-macosx-finder --enable-apple-remote
==> make install
    needed = self.resolve(parse_requirements(requirements))
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources.py", line 565, in resolve
    raise DistributionNotFound(req)  # XXX put more info here
pkg_resources.DistributionNotFound: docutils==0.8.1
make: *** [DOCS/man/en/mplayer.1] Error 1
```

Prior to that it installed Py3 which is not the first one in my path and should be the reason for this issue. I depend on 2.7 cause of some scripts and I got version 3.2 of Py already installed but not linked (from python.org). Is it possible to point mplayer2 to this install without changing the default py version?

I'm a bit confused cause I installed mplayer2 a while ago without any problems. I removed it in order to reinstall with ffmpeg. :/

**Comment by pigoz** [comment]
Looks like docutils is not installed on your system python… let me know if this helps.

**Comment by Argon-** [comment]
Indeed it works. brew wanted me to link py3 what I ignored with `--ignore-dependencies`. A quick run was successful so I hope the unlinked py3 won't have a negative impact later on. Thanks!
