### ISSUE TITLE
mplayer2.app crash on startup; Incompatible library version

### ISSUE THREAD

**Issue by Argon-** [pigoz/homebrew-mplayer2#12]
libfreetype.6.dylib bundeled within mplayer2.app is of compatibility version 15 while libass requires 16.

```
Dyld Error Message:
  Library not loaded: @executable_path/lib/libfreetype.6.dylib
  Referenced from: /usr/local/Cellar/mplayer2/HEAD/mplayer2.app/Contents/MacOS/lib/libass.4.dylib
  Reason: Incompatible library version: libass.4.dylib requires version 16.0.0 or later, but libfreetype.6.dylib provides version 15.0.0
```

Replacing the lib inside the bundle with e.g. the self brewed libfreetype solves the problem (homebrew ships 2.4 with compatibility version 16).

**Comment by pigoz** [comment]
Please can you paste the result of `otool -L /usr/local/lib/libass.dylib`? Seems like something is broken on your configuration.

**Comment by Argon-** [comment]
The libass is installed with brew (most recent version)

```
/usr/local/lib/libass.dylib:
    /usr/local/lib/libass.4.dylib (compatibility version 6.0.0, current version 6.0.0)
    /usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 169.3.0)
    /usr/lib/libiconv.2.dylib (compatibility version 7.0.0, current version 7.0.0)
    /usr/local/lib/libfreetype.6.dylib (compatibility version 16.0.0, current version 16.0.0)
    /usr/local/lib/libfribidi.0.dylib (compatibility version 4.0.0, current version 4.1.0)
    /usr/local/lib/libfontconfig.1.dylib (compatibility version 8.0.0, current version 8.2.0)
```

But my local libass shouldn't matter, should it? The libass requesting a version 16 freetype was the one bundled in mplayer2.app:
`Referenced from: /usr/local/Cellar/mplayer2/HEAD/mplayer2.app/Contents/MacOS/lib/libass.4.dylib`
Ich checked the libfreetype inside the bundle and it referenced a compatibility version of 15. Can't show you the output though, already replaced it with libfreetype from homebrew.

**Comment by pigoz** [comment]
You just made the `mplayer2.app` bundle with the formula right? If that's true you should already be running a modified version of your homebrew's `libfreetype`. `make osxbundle` just runs `otool` and `install_name_tool`. Do you happen to have X11 installed as well?

**Comment by Argon-** [comment]
Yes and I attempt to reinstall with _renamed_ /opt/X11

```
$ brew install mplayer2 --HEAD --ignore-dependencies 
==> Cloning git://git.mplayer2.org/mplayer2.git
Updating /Library/Caches/Homebrew/mplayer2--git
==> Generating VERSION file from Homebrew's git cache
==> ./configure --prefix=/usr/local/Cellar/mplayer2/HEAD --cc=cc --enable-macosx-bundle --enable-macosx-finder --disable-x11
==> make install
==> make osxbundle
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "/usr/local/Cellar/python3/3.3.0/Frameworks/Python.framework/Versions/3.3/lib/python3.3/shutil.py", line 109, in copyfile
    with open(src, 'rb') as fsrc:
FileNotFoundError: [Errno 2] No such file or directory: '/usr/X11/lib/libfreetype.6.dylib'
make: *** [osxbundle] Error 1
```

To be honest I've got no idea how to change the search path order for libraries on OS X.
Since freetype is a dependency of mplayer2, why not taking straight away the one in $(brew --prefix)/lib?

**Comment by pigoz** [comment]
The osxbundle is generated by mplayer2, so it can't be linked to homebrew.
I'm sure people using MacPorts, or building manually can make a good use of
it as well.

As for overriding the libraries search path it's generally in the env
variable $DYLIB_LIBRARY_PATH. I'll try to reproduce. On my system it builds
a working version of the bundle.

**Comment by Argon-** [comment]
I guess you had no success? Funny thing: I tried it a few hours ago and there was no problem. Seems like I accidentally fixed it or something else changed. Thanks. :)

**Comment by pigoz** [comment]
Well, I backported some changes from mpv-player/homebrew-mpv a month ago, so that might had the side effect of fixing this problem for you. Btw, I'm terribly sorry I forgot about this issue :)
