### ISSUE TITLE
Wrong Python version used

### ISSUE THREAD

**Issue by Argon-** [pigoz/homebrew-mplayer2#13]
Sorry to bug you again but I don't know where the problem is located. How does the formula determine the python version to use?
##### Config

My setup is probably kind of messed up. I have the formula `python` installed & linked with homebrew, `python3` installed but not linked since a few things rely on 2.7. At the same time there is

```
$ ls -lha /Library/Frameworks/Python.framework/Versions/
drwxrwxr-x  10 root  admin   340B 10 Apr  2012 2.7/
drwxrwxr-x   9 root  admin   306B  4 Sep  2011 3.2/
lrwxr-xr-x   1 root  wheel     3B  6 Feb 19:25 Current@ -> 2.7
```

but none of them is linked to any bin/ directory. `$PATH = /usr/local/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin:/usr/texbin:/usr/local/mysql/bin:/usr/local/gcc/gcc471/bin:/usr/local/depot_tools:/opt/local/bin:/opt/local/sbin`
`brew doctor` is fine, only complaining about a few libraries I needed for compiling gcc (gmp, mpfr, gomp, libntfs and libosxfuse) and the not linked python3.
##### Problem

My error results during 'make osxbundle' by the usage of the wrong python version:

```
$ brew install mplayer2 --HEAD --ignore-dependencies 
==> Cloning git://git.mplayer2.org/mplayer2.git
Updating /Library/Caches/Homebrew/mplayer2--git
==> Generating VERSION file from Homebrew's git cache
==> ./configure --prefix=/usr/local/Cellar/mplayer2/HEAD --cc=cc --enable-macosx-bundle --enable-macosx-finder --disable-x11
==> make install
==> make osxbundle
    restore_signals, start_new_session)
  File "/Library/Frameworks/Python.framework/Versions/3.2/lib/python3.2/subprocess.py", line 1193, in _execute_child
    restore_signals, start_new_session, preexec_fn)
OSError: [Errno 35] Resource temporarily unavailable
make: *** [osxbundle] Error 1
```

Why does he use this version of python? It is nowhere in my PATH (shouldn't be). Renaming the folder of this version leads to a total different error:

```
$ brew install mplayer2 --HEAD --ignore-dependencies 
==> Cloning git://git.mplayer2.org/mplayer2.git
Updating /Library/Caches/Homebrew/mplayer2--git
==> Generating VERSION file from Homebrew's git cache
==> ./configure --prefix=/usr/local/Cellar/mplayer2/HEAD --cc=cc --enable-macosx-bundle --enable-macosx-finder --disable-x11
==> make install
brew: superenv removed: -Wall -Wno-switch-enum -Wno-logical-op-parentheses -Wpointer-arith -Wundef -Wno-pointer-sign -Wmissing-prototypes -Werror=implicit-function-declaration -O2 -march=core2
brew: superenv removed: -Wall -Wno-switch-enum -Wno-logical-op-parentheses -Wpointer-arith -Wundef -Wno-pointer-sign -Wmissing-prototypes -Werror=implicit-function-declaration -O2 -march=core2
brew: superenv removed: -Wall -Wno-switch-enum -Wno-logical-op-parentheses -Wpointer-arith -Wundef -Wno-pointer-sign -Wmissing-prototypes -Werror=implicit-function-declaration -O2 -march=core2
brew: superenv removed: -Wall -Wno-switch-enum -Wno-logical-op-parentheses -Wpointer-arith -Wundef -Wno-pointer-sign -Wmissing-prototypes -Werror=implicit-function-declaration -O2 -march=core2
brew: superenv removed: -Wall -Wno-switch-enum -Wno-logical-op-parentheses -Wpointer-arith -Wundef -Wno-pointer-sign -Wmissing-prototypes -Werror=implicit-function-declaration -O2 -march=core2
```

**Comment by Argon-** [comment]
Hilarious. Wasted the last few hours cause I missed a single link in /usr/local/bin which refused to get deleted cause of insufficient permissions (and I missed the error message). Sorry, problem located solely on my end. :S

**Comment by pigoz** [comment]
Keep in mind that `make osxbundle` always uses `python3` in mplayer2. mpv uses `python` and that's generally the system's python 2.7.

I'm glad you solved it. I think homebrew should be able to report you problems with directories permissions with `brew doctor`.
