### ISSUE TITLE
`make osxbundle` fails: Missing `liblua.5.1.4.dylib`

### ISSUE THREAD

**Issue by jvilk** [pigoz/homebrew-mplayer2#14]
`/usr/local/lib/liblua.5.1.4.dylib` has been replaced with `/usr/local/lib/liblua.5.1.5.dylib` with the latest brew upgrades, so the `make osxbundle` fails.

It would be a better idea if the installer used the `/usr/local/lib/liblua.5.1.dylib` or the `/usr/local/lib/liblua.dylib` symlinks that brew maintains, as it will be auto-updated to new versions.

```
$ brew install --HEAD pigoz/mplayer2/mplayer2
==> Cloning git://git.mplayer2.org/mplayer2.git
Updating /Library/Caches/Homebrew/mplayer2--git
==> Generating VERSION file from Homebrew's git cache
==> ./configure --prefix=/usr/local/Cellar/mplayer2/HEAD --cc=cc --enable-macosx
==> make install
==> make osxbundle
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "/usr/local/Cellar/python3/3.3.0/Frameworks/Python.framework/Versions/3.3/lib/python3.3/shutil.py", line 109, in copyfile
    with open(src, 'rb') as fsrc:
FileNotFoundError: [Errno 2] No such file or directory: '/usr/local/lib/liblua.5.1.4.dylib'
make: *** [osxbundle] Error 1
```

I actually couldn't find the source of this dependency (I've never poked at a formula before), but I imagine it has to be referencing this particular version somewhere.

**Comment by jvilk** [comment]
AHA! I had to reinstall `libquvi`, which referenced an older version of `liblua`. I have **no idea** why it wasn't upgraded or fixed automatically by homebrew.

My fault.

**Comment by pigoz** [comment]
As you found out some of your dependencies were still using /usr/local/lib/liblua.5.1.4.dylib. The `make osxbundle` script just uses `otool -L` on the binary and the recursively on the linked libraries. IIRC I made the error message a little nicer in [mpv's](http://mpv.io/) `make osxbundle`.

**Comment by jvilk** [comment]
Yeah, I had no idea where it was coming from; `brew doctor` apparently doesn't check for this sort of issue. It's good to have `mplayer2` back, though.
