### ISSUE TITLE
libav build fails - ERROR: freetype2 not found 

### ISSUE THREAD

**Issue by victorhooi** [pigoz/homebrew-mplayer2#2]
I just tried to follow the libav step:

```
brew install --HEAD pigoz/mplayer2/libav
```

However, it errors out on the configure step.

I've attached my config.log here:

https://gist.github.com/3560433

It seems to be requiring freetype2

This is on OSX 10.8.1 - I did a quick search using mdfind, and I do seem to have the ft2build.h file at:

```
/opt/X11/include/ft2build.h
```

and freetype.h at:

```
/opt/X11/include/freetype2/freetype/freetype.h
```

Cheers,
Victor

**Comment by pigoz** [comment]
Hello Victor, thanks for reporting!
Should now be fixed in 188d8b887b2bcfbb75e194af37ed1cd1cbd1d202. Please try again.
